# Generated by Django 3.0.6 on 2021-02-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('shelf_number', models.PositiveIntegerField()),
                ('row_number', models.PositiveIntegerField()),
                ('date_of_entry', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Books',
            },
        ),
    ]
